#!/bin/bash

echo "Starting hotreload..."
tmux send-keys -t 1 C-c
sleep 0.5
tmux send-keys -t 1 clear C-m
sleep 0.2
tmux send-keys -t 1 "go run ." C-m
sleep 0.2

tmux send-keys -t 2 C-c
sleep 0.5
tmux send-keys -t 2 clear C-m
sleep 0.2
tmux send-keys -t 2 "tail -f logs/latest.log" C-m
sleep 0.2
