#!/bin/bash

#
# TODO: Add description about this script 
#

# INFO:
# set -e or set -o errexit: if there is an error, then exit immediately.
# set -u or set -o nounset: disallow unset variables.
# set -f or set -o noglob: disable filename globbing.
# set -o pipefail: if a pipe fails, then exit immediately and use the pipe's exit status.

set -euo pipefail

EXECUTABLE_PATH=".build/lazytask"

if [ ! -f "$EXECUTABLE_PATH" ]; then
  ./build

  if [ ! -f "$EXECUTABLE_PATH" ]; then
    echo "Error: Executable not found."
    exit 1
  fi
fi

.build/./lazytask

exit 0
